apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
  labels:
    app: django-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
      - name: django
        image: kanimozhimurugesan197/library-management-system:latest
        ports:
          - containerPort: 80
        env:
          - name: DB_HOST
            value: "mysql"
          - name: DB_PORT
            value: "3306"
          - name: DB_NAME
            value: "mydb"
          - name: DB_USER
            value: "N01563837W25"
          - name: DB_PASSWORD
            value: "Toronto@2024"
