# Generated by Django 4.2.20 on 2025-03-31 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('User_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=100)),
                ('Membership_status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Users',
                'managed': False,
            },
        ),
    ]
